name: movie_chi
description: a movies app with movie chi
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.86-release+68

environment:
  sdk: ">=2.17.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  sqflite:
  visibility_aware_state: ^1.0.5
  flutter_archive: ^5.0.0
  flutter_typeahead: ^4.6.2
  expandable: ^5.0.1
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  font_awesome_flutter: ^10.6.0
  flutter_image_slideshow: ^0.1.2
  cached_network_image: ^3.2.1
  get: ^4.6.5
  url_launcher: ^6.2.1
  dropdown_button2: ^1.6.3
  lottie: ^1.4.3
  http: ^1.1.0
  pod_player: ^0.2.1
  check_vpn_connection: ^0.0.2
  flutter_statusbarcolor_ns: ^0.4.0
  photo_view: ^0.14.0
  # package_info_plus: ^1.4.3+1
  dio: ^5.3.2
  system_info2: ^2.0.4
  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  status_bar_control: ^3.2.1
  iconsax: ^0.0.8
  adaptive_theme: ^3.1.1
  salomon_bottom_bar: ^3.3.1 
  shimmer: ^2.0.0
  carousel_slider:
  persian_number_utility: ^1.1.2
  fluttertoast: ^8.1.1
  # flutter_svg: ^2.0.4
  device_info_plus: ^8.1.0
  platform_device_id: ^1.0.1
  visibility_detector: 
  loading_animation_widget: ^1.2.0+4
  pinput:
  share_plus: ^7.1.0
  # flutter_meedu_videoplayer: 
  #   git: 
  #     url: https://github.com/zezo357/flutter_meedu_videoplayer.git
  #     ref: 368702e0298089e714164fe0c3ba9b45463965ed
  #     path: package/
  uni_links: ^0.5.1
  pull_to_refresh_flutter3: ^2.0.1
  swipeable_page_route: ^0.3.1
  window_manager: ^0.3.4
  flutter_web_frame: ^0.0.3
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  # universal_html: 
  badges: ^3.1.1
  # image_gallery_saver: ^2.0.2
  firebase_core: ^2.18.0
  firebase_messaging: ^14.6.5
  platform_local_notifications: ^0.0.4
  # google_mobile_ads: ^3.0.0
  pinch_zoom: ^1.0.0
  icons_plus: ^4.0.0
  package_info_plus: ^4.1.0
  wakelock_plus: ^1.1.1
  flutter_screenutil: ^5.8.4
  appcheck: ^1.0.6
  preload_page_view: ^0.2.0
  firebase_auth: ^4.11.0
  google_sign_in: ^6.1.6
  easy_loading_button: ^0.3.2
  confetti: ^0.7.0
  media_kit: ^1.1.10                             # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_libs_video: ^1.0.4                   # Native video dependencies.          # Native video dependencies.
  gap: ^3.0.1
  flutter_dotenv: ^5.1.0
  flutter_animate: ^4.5.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2 


flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/lotties/
    - assets/images/
    - assets/local.db
    - .env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: vazir
      fonts:
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
          
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
          
        - asset: assets/fonts/Vazirmatn-Light.ttf
          weight: 300
          
        - asset: assets/fonts/Vazirmatn-Thin.ttf
          weight: 100
        - asset: assets/fonts/Vazirmatn-Black.ttf
          weight: 900
        - asset: assets/fonts/Vazirmatn-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Vazirmatn-ExtraLight.ttf
          weight: 200
        


        
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


