import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';

import '../../../../../core/utils/constants.dart';
import '../../../data/model/grid_model.dart';
import '../../../data/model/home_catagory_model.dart';

class GridHomeViewController {
  List convertModelToListIds(HomeCatagoryItemModel homeCatagoryItem) {
    List videoIDS = [];
    for (var element in homeCatagoryItem.data!) {
      videoIDS.add(element.id);
    }
    return videoIDS;
  }

  Dio dio = Dio();

  onloadingMore(HomeCatagoryItemModel homeCatagoryItem) async {
    // sleet 5 sec for loading

    List videoIDS = convertModelToListIds(homeCatagoryItem);

    var res = await dio.post("${Constants.baseUrl()}${pageUrl}play_list.php",
        queryParameters: {
          "video_ids": json.encode(videoIDS.toString()),
          "keyWord": homeCatagoryItem.title,
          "playlist_id": homeCatagoryItem.id,
          "playlist_type": "more_autogenerated",
        });

    if (res.statusCode == 200) {
      GridModel gridModel = GridModel.fromJson(json.decode(res.data));

      for (var element in gridModel.data!) {
        homeCatagoryItem.data!.add(element);
      }

      // homeCatagoryItem.data!.addAll(gridModel.data!);
    } else {
      debugPrint("error");
    }
  }
}
